<?xml version="1.0"?>

<!--
* Software License Agreement (BSD License)
*
* Copyright (c) 2010, Antons Rebguns. All rights reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions
* are met:
*
*  * Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*  * Redistributions in binary form must reproduce the above
*    copyright notice, this list of conditions and the following
*    disclaimer in the documentation and/or other materials provided
*    with the distribution.
*  * Neither the name of University of Arizona nor the names of its
*    contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
* BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
* CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
* ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.

* Author: Antons Rebguns
-->

<robot
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <property name="M_SCALE" value="0.001 0.001 0.001"/>
    <property name="G_offset" value="0.15"/>
    <material name="Grey">
      <color rgba="0.5 0.5 0.5 1.0"/>
    </material>
    <material name="DarkGrey">
      <color rgba="0.3 0.3 0.3 1.0"/>
    </material>
    <material name="Red">
      <color rgba="0.9 0.2 0.2 1.0"/>
    </material>
    <material name="Blue">
      <color rgba="0.2 0.2 0.9 1.0"/>
    </material>

    <macro name="ax12_arm" params="parent *origin">
        <!-- ****** JOINT DEFINITIONS ****** -->
        

        <joint name="arm_base_joint" type="fixed">
            <insert_block name="origin" /> 
            <parent link="${parent}"/>
            <child link="arm_base_link"/>
        </joint>
        

        <joint name="shoulder_pan_joint" type="revolute" >
            <origin xyz="-0.0075 0 0.025" rpy="0 0 0" />
            <parent link="arm_base_link" />
            <child link="arm_shoulder_pan_link"/>
            
            <axis xyz="0 0 1"/>
            <limit  lower="-1.6" upper="1.6" effort="300" velocity="0.4" />
            <safety_controller k_position="100" k_velocity="15.0" soft_lower_limit="${-1.22+0.1}" soft_upper_limit="${1.22-0.1}" />
            <dynamics damping="50" friction="1"/>
        </joint>
        

        <joint name="shoulder_pitch_joint" type="revolute">
            <origin xyz="0.044 0 0.090" rpy="0 -0.7854 0" />
            <parent link="arm_shoulder_pan_link"/>
            <child link="arm_shoulder_pitch_link" />
            
            <axis xyz="0 1 0"/>
            <limit  lower="-1.5" upper="1.2" effort="300" velocity="0.4" />
            <safety_controller k_position="100" k_velocity="15.0" soft_lower_limit="${-1.04719755+0.1}" soft_upper_limit="${1.972222-0.1}" />
            <dynamics damping="50" friction="1"/>
        </joint>
        

        <joint name="elbow_flex_joint" type="revolute">
            <origin xyz="${0.04 - 0.01 + 0.0015 + 0.105 + 0.055 - 0.01} 0 0" rpy="0 0 0" />
            <parent link="arm_shoulder_pitch_link"/>
            <child link="arm_elbow_flex_link" />
            
            <axis xyz="0 -1 0"/>
            <limit  lower="-1.5" upper="1.5" effort="300" velocity="0.4" />
            <dynamics damping="50" friction="1"/>
            <safety_controller k_position="100" k_velocity="15.0" soft_lower_limit="${-1.972222+0.1}" soft_upper_limit="${1.8849556-0.1}" />
        </joint>
        

        <joint name="wrist_roll_joint" type="revolute">
            <origin xyz="${0.08 - 0.01} 0 ${0.05 - 0.0115 - 0.0155}" rpy="3.14159 0 0" />
            <parent link="arm_elbow_flex_link"/>
            <child link="gripper_roll_link" />
            
            <axis xyz="1 0 0"/>
            <limit  lower="-1.5" upper="1.5" effort="300" velocity="1.17" />
            <dynamics damping="50" friction="1"/>
            <safety_controller k_position="100" k_velocity="15.0" soft_lower_limit="${-2.6179939+0.1}" soft_upper_limit="${2.6179939-0.1}" />
        </joint>
        
        
        <!-- ****** LINK DEFINITIONS ****** -->
        
        <link name="arm_base_link">
            <inertial>
                <mass value="0.125" />
                <origin xyz="0 0 0.00893364" rpy="0 0 0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0" 
                         izz="1.0" />
            </inertial>
            
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://ax12_description/meshes/stl/arm_base.stl"/>
                </geometry>
                <material name="Grey" />
            </visual>
            
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://ax12_description/meshes/stl/arm_base.stl"/>
                </geometry>
            </collision>
        </link>
        
        <link name="arm_shoulder_pan_link">
            <inertial>
                <mass value="0.405" />
                <origin xyz="0.02988871 0 0.02056699" rpy="0 0 0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0" 
                         izz="1.0" />
            </inertial>
            
            <visual>
                <origin xyz="0.0 0.0 0.005" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://ax12_description/meshes/stl/arm_shoulder_pan_new.stl"/>
                </geometry>
                <material name="DarkGrey" />
            </visual>
            
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://ax12_description/meshes/stl/arm_shoulder_pan_new.stl"/>
                </geometry>
            </collision>
        </link>
        
        <link name="arm_shoulder_pitch_link">
            <inertial>
                <mass value="0.18" />
                <origin xyz="0.13999458 0 0.00064711" rpy="0 0 0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0" 
                         izz="1.0" />
            </inertial>
            
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://ax12_description/meshes/stl/arm_shoulder_pitch.stl"/>
                </geometry>
                <material name="Grey" />
            </visual>
            
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://ax12_description/meshes/stl/arm_shoulder_pitch.stl"/>
                </geometry>
            </collision>
        </link>
        
        <link name="arm_elbow_flex_link">
            <inertial>
                <mass value="0.12" />
                <origin xyz="0.04463361 0 0.00720194" rpy="0 0 0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0" 
                         izz="1.0" />
            </inertial>
            
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://ax12_description/meshes/stl/arm_elbow_flex.stl"/>
                </geometry>
                <material name="DarkGrey" />
            </visual>
            
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://ax12_description/meshes/stl/arm_elbow_flex.stl"/>
                </geometry>
            </collision>
        </link>
        
        
        
        <!-- ****** TRANSMISSION DEFINITIONS ****** -->
        
        <transmission type="pr2_mechanism_model/SimpleTransmission" name="shoulder_pan_trans">
            <actuator name="shoulder_pan_motor" />
            <joint name="shoulder_pan_joint" />
            <mechanicalReduction>1.0</mechanicalReduction>
        </transmission>
        
        <transmission type="pr2_mechanism_model/SimpleTransmission" name="shoulder_pitch_trans">
            <actuator name="shoulder_pitch_motor" />
            <joint name="shoulder_pitch_joint" />
            <mechanicalReduction>1.0</mechanicalReduction>
        </transmission>
        
        <transmission type="pr2_mechanism_model/SimpleTransmission" name="elbow_flex_trans">
            <actuator name="elbow_flex_motor" />
            <joint name="elbow_flex_joint" />
            <mechanicalReduction>1.0</mechanicalReduction>
        </transmission>
        
        <transmission type="pr2_mechanism_model/SimpleTransmission" name="wrist_roll_trans">
            <actuator name="wrist_roll_motor" />
            <joint name="wrist_roll_joint" />
            <mechanicalReduction>1.0</mechanicalReduction>
        </transmission>
        
        
        
        <!-- ****** MATERIAL DEFINITIONS ****** -->
        
        <gazebo reference="arm_base_link">
            <material>Gazebo/Grey</material>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>
        
        <gazebo reference="arm_shoulder_pan_link">
            <material>Gazebo/Grey</material>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>
        
        <gazebo reference="arm_shoulder_pitch_link">
            <material>Gazebo/Grey</material>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>
        
        <gazebo reference="arm_elbow_flex_link">
            <material>Gazebo/Grey</material>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>
        
        
        <gazebo reference="shoulder_pan_joint">
            <stopKd value="1.0" />
            <stopKp value="1000000.0" />
            <fudgeFactor value="0.5" />
        </gazebo>
        
        <gazebo reference="shoulder_pitch_joint">
            <stopKd value="1.0" />
            <stopKp value="1000000.0" />
            <fudgeFactor value="0.5" />
        </gazebo>
        
        <gazebo reference="elbow_flex_joint">
            <stopKd value="1.0" />
            <stopKp value="1000000.0" />
            <fudgeFactor value="0.5" />
        </gazebo>
        
        <!-- GRIPPER ROLL LINK -->
  <link name="gripper_roll_link">

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="1.0" />
      <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="1.0"  iyz="0.0"  izz="1.0" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://ax12_description/meshes/stl/gripper_roll_link_scaled.stl" />
      </geometry>
      <material name="Grey" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://ax12_description/meshes/stl/gripper_roll_link_scaled.stl" />
      </geometry>
    </collision>

  </link>

  <gazebo reference="gripper_roll_link">
    <material>Gazebo/Grey</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
  
        <joint name="gripper_joint" type="revolute">
          <parent link="gripper_roll_link"/>
          <child link="gripper_finger_link"/>
          <origin xyz="0.026 0.018  0" rpy="${2.73 - G_offset} ${3.14159/2} ${34.58*3.14159/180}" />
          <axis xyz="1 0 0" />
          <limit effort="300" velocity="1" lower="-0.15" upper="0.55"/>
          <dynamics damping="50" friction="1"/>
        </joint>


        <link name="gripper_finger_link">

          <inertial>
            <origin xyz="0 0 0"  />
            <mass value="1.0" />
            <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="1.0"  iyz="0.0"  izz="1.0" />
          </inertial>

          <visual>
            <origin xyz="0 0 0" rpy="0 0 ${3.14159}" />
            <geometry>
              <mesh filename="package://ax12_description/meshes/stl/l_gripper_aft_link.STL" />
            </geometry>
            <material name="Blue" />
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 ${3.14159}" />
            <geometry>
              <mesh filename="package://ax12_description/meshes/stl/l_gripper_aft_link.STL" />
            </geometry>
          </collision>

        </link>

        <gazebo reference="gripper_finger_link">
          <material>Gazebo/Blue</material>
          <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <joint name="r_gripper_aft_joint" type="revolute">
          <parent link="gripper_roll_link"/>
          <child link="r_gripper_aft_link"/>
          <origin xyz="0.026 -0.011  0" rpy="${-1.5 + G_offset} ${3.14159/2} ${34.58*3.14159/180}" />
          <axis xyz="1 0 0" />
          <limit effort="300" velocity="1" lower="-0.55" upper="0.15" />
          
          <dynamics damping="50" friction="1"/>
        </joint>


        <link name="r_gripper_aft_link">

          <inertial>
            <origin xyz="0 0 0"  />
            <mass value="1.0" />
            <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="100.0"  iyz="0.0"  izz="1.0" />
          </inertial>

          <visual>
            <origin xyz="0 0 0" rpy="0 0 ${3.14159}" />
            <geometry>
              <mesh filename="package://ax12_description/meshes/stl/r_gripper_aft_link.STL" />
            </geometry>
            <material name="Blue" />
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 ${3.14159}" />
            <geometry>
              <mesh filename="package://ax12_description/meshes/stl/r_gripper_aft_link.STL" />
            </geometry>
          </collision>

        </link>

        <gazebo reference="r_gripper_aft_link">
          <material>Gazebo/Blue</material>
          <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <joint name="l_gripper_fwd_joint" type="revolute">
          <parent link="gripper_roll_link"/>
          <child link="l_gripper_fwd_link"/>
          <origin xyz="0.05 0.008 0.007" rpy="${2.75 - G_offset} ${3.14159/2} ${214.58*3.14159/180}" />
          <axis xyz="1 0 0" />
          <limit effort="300" velocity="1" lower="-0.15" upper="0.55" />
          <dynamics damping="50" friction="1"/>
        </joint>


        <link name="l_gripper_fwd_link">

          <inertial>
            <origin xyz="0 0 0"  />
            <mass value="1.0" />
            <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="100.0"  iyz="0.0"  izz="1.0" />
          </inertial>

          <visual>
            <origin xyz="0 0 0" rpy="0 0 ${3.14159}" />
            <geometry>
              <mesh filename="package://ax12_description/meshes/stl/l_gripper_fwd_link.STL" />
            </geometry>
            <material name="Blue" />
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 ${3.14159}" />
            <geometry>
              <mesh filename="package://ax12_description/meshes/stl/l_gripper_fwd_link.STL" />
            </geometry>
          </collision>

        </link>

        <gazebo reference="l_gripper_fwd_link">
          <material>Gazebo/Blue</material>
          <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <joint name="r_gripper_fwd_joint" type="revolute">
          <parent link="gripper_roll_link"/>
          <child link="r_gripper_fwd_link"/>
          <origin xyz="0.05 -0.0014 0.007" rpy="${3.55 + G_offset} ${3.14159/2} ${145.42*3.14159/180}" />
          <axis xyz="1 0 0" />
          <limit effort="300" velocity="1" lower="-0.55" upper="0.15" />
          <dynamics damping="50" friction="1"/>
        </joint>


        <link name="r_gripper_fwd_link">

          <inertial>
            <origin xyz="0 0 0"  />
            <mass value="1.0" />
            <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="100.0"  iyz="0.0"  izz="1.0" />
          </inertial>

          <visual>
            <origin xyz="0 0 0" rpy="0 0 ${3.14159}" />
            <geometry>
              <mesh filename="package://ax12_description/meshes/stl/r_gripper_fwd_link.STL" />
            </geometry>
            <material name="Blue" />
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 ${3.14159}" />
            <geometry>
              <mesh filename="package://ax12_description/meshes/stl/r_gripper_fwd_link.STL" />
            </geometry>
          </collision>


        </link>

        <gazebo reference="r_gripper_fwd_link">
          <material>Gazebo/Blue</material>
          <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <joint name="gripper_finger_pincher_joint" type="revolute">
          <parent link="gripper_finger_link"/>
          <child link="l_gripper_pincher_link"/>
          <origin xyz="-0.0032 0 -0.0508" rpy="${-3.14159 + G_offset} 0 0" />
          <axis xyz="1 0 0" />
          <limit effort="300" velocity="1" lower="-0.55" upper="0.15" />
          <dynamics damping="50" friction="1"/>
        </joint>


        <link name="l_gripper_pincher_link">

          <inertial>
            <origin xyz="0 0 0"  />
            <mass value="1.0" />
            <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="100.0"  iyz="0.0"  izz="1.0" />
          </inertial>

          <visual>
            <origin xyz="0 0 0" rpy="0 0 ${3.14159}" />
            <geometry>
              <mesh filename="package://ax12_description/meshes/stl/l_gripper_pincher.STL" />
            </geometry>
            <material name="Red" />
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 ${3.14159}" />
            <geometry>
              <mesh filename="package://ax12_description/meshes/stl/l_gripper_pincher.STL" />
            </geometry>
          </collision>

        </link>

        <gazebo reference="l_gripper_pincher_link">
          <material>Gazebo/Red</material>
          <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <joint name="r_gripper_aft_pincher_joint" type="revolute">
          <parent link="r_gripper_aft_link"/>
          <child link="r_gripper_pincher_link"/>
          <origin xyz="0 0 -0.0508" rpy="${0.00 + G_offset} ${3.14159} 0" />
          <axis xyz="1 0 0" />

          <limit effort="300" velocity="1" lower="-0.55" upper="0.15" />
          <dynamics damping="50" friction="1"/>
        </joint>


        <link name="r_gripper_pincher_link">

          <inertial>
            <origin xyz="0 0 0" />
            <mass value="1.0" />
            <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="100.0"  iyz="0.0"  izz="1.0" />
          </inertial>

          <visual>
            <origin xyz="0 0 0" rpy="0 0 ${3.14159}" />
            <geometry>
              <mesh filename="package://ax12_description/meshes/stl/r_gripper_pincher.STL" />
            </geometry>
            <material name="Red" />
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 ${3.14159}" />
            <geometry>
              <mesh filename="package://ax12_description/meshes/stl/r_gripper_pincher.STL" />
            </geometry>
          </collision>

        </link>

        <gazebo reference="r_gripper_pincher_link">
          <material>Gazebo/Red</material>
          <turnGravityOff>false</turnGravityOff>
        </gazebo>
        
    </macro>
</robot>
