controller_list:
  - name: fake_ax_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_pitch_joint
      - elbow_flex_joint
      - wrist_roll_joint
  - name: fake_ax_eef_controller
    joints:
      - gripper_joint
      - gripper_finger_pincher_joint
      - l_gripper_fwd_joint
      - r_gripper_aft_joint
      - r_gripper_aft_pincher_joint
      - r_gripper_fwd_joint